# SPDX-FileCopyrightText: © 2025 Christoph Görn <goern@b4mad.net>
# SPDX-License-Identifier: GPL-3.0-only

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: agentllm-base

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: agentllm
      app.kubernetes.io/component: llm-proxy

resources:
  - deployment.yaml
  - service.yaml
