apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: open-webui-base

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: agentllm
      app.kubernetes.io/component: openwebui

resources:
  - deployment.yaml
  - persistent_volume_claim.yaml
  - service_account.yaml
  - service.yaml
