# SPDX-FileCopyrightText: © 2025 Christoph Görn <goern@b4mad.net>
# SPDX-License-Identifier: GPL-3.0-only

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: agentllm-prod

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/environment: production

resources:
  - ../../base

replicas:
  - name: agentllm
    count: 2

images:
  - name: codeberg.org/b4mad/agentllm/agentllm
    newTag: stable

patches:
  - target:
      kind: Deployment
      name: agentllm
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "4000m"
