# SPDX-FileCopyrightText: © 2025 Christoph Görn <goern@b4mad.net>
# SPDX-License-Identifier: GPL-3.0-only
apiVersion: v1
kind: Secret
metadata:
    name: agentllm
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:9W2ULoc22Xcao1j4zpjv0u5vIQhSKq9Y7wXiiwJsFyMJnDUwlgScZhjkR93KjPpkg/q+ceIoG1etyqAFjm9O/bUgxgx6TuIs6c4/4YZ67Q6fQ8+dfn32QVGuLeJ+vMm93gbEvztrEFktuwit,iv:UyJMWzZ/U4HNgHxTCmW0VbHnHwFFMWMnQ+sPGzOHPuE=,tag:0aEWO0fRnb+p1FOvRAkFzw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:R7yaSRyyZgCciWsK3xCMTmXY6Ezw8OU5bsbtusvvGg/HxqHweXeqNWLnYbCOsJ+JFiK0UqFvR3uuB3HoxQ5GqTyEtjak8+/8yA==,iv:m2b8K/1Ir452PlYcl2K9GFusidcQyydJM4763nzCoyY=,tag:n+mLo6cAg1eM5BXTur4CxA==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:9/12Y2sMm9QnMAYDDrmJWxxbuWVXSQ==,iv:aVEKmTKfdWYM4vlzluZyMKjQMSWkB95yi5R/g9ZSPDc=,tag:mwHlk6jDVJgsIDhOZ7TdEA==,type:str]
    LITELLM_API_KEY_BEARER: ENC[AES256_GCM,data:7S4+93/kfPT2xAQowNjjWHRMThIs3limO/7TFc0=,iv:grVzscyC65Aq8cnQH7DJFT9ZD9kWftvJ17RlCdN0b0M=,tag:t+NYFPBL7V7jKLG8zuTxqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-09T12:34:58Z"
    mac: ENC[AES256_GCM,data:RAqhY8sJuSn5aG93X1jQzVaYJswlqiTCyC9UTlALiZMvCgLnVH4l8fiNRIScaxiAzubfinSoMGq48EmuGvbpzBA44POT/YiopGNtiPBp6+4GxwCmEMQ03u5vXtOL8uBRkrmd22f/l6YmhTuXF8UguVm+u+W68YwpJxogJfvMqAE=,iv:rvxgjOio7/mUbYGXlQghwBLmtsjt3StqAGDPTkNW08M=,tag:rYHg+CUDM17BKKm/+2hDOQ==,type:str]
    pgp:
        - created_at: "2025-11-09T10:45:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+XrDaMvM3KsAQ//RXIks54j/0GqLGHArl3lBqa2Z+m1GDndRIxeps0aQDy0
            iNOZnzf7mtMvK+NViK3zu2278NdcEMJXnSaL6fBw5fftqnhhwgQYbL/rm4XVydla
            iEPUzUNywiD8w8SSpPn1lt5hVg6I1zlAAeWP6R5J/bQRSbBnfyT5w7TYREVJ+/Tu
            oPEuq84y2Cgs1/tefd/XiXOliYyLFbvf0CVkQlGXP2B6e+DA7FzpV69n7P/rwe8G
            RKB0FXpUyncNi4ZzCAPVLq/VfncmKPX+aeDnIO6jfTthmi2+3+9VB1PGqaTvRft6
            qm9Yca+j1oQIg+i+VyjNE4J4W7KKlvh37AnoTKahlCZkHg5xA84U9g067l7bDhxV
            GbafXM9S3M0HouysGthnLuM1j3xk5fc8Cj3DEy0Qf6J7Ris7/YVUJZWm8Qh8dafN
            kU0I7pS2EMJfZvJdzGAEdG3MkTFcPdTveKCoqRoH/3SNP0gstCUk/BIjW5oKKo3t
            Mw9rIZM8pxBaeuybwSjAgCLfVoQGrUbBU4tPxTHHCgnDgj8TzIRTrmCG6lWpC6s8
            CiCUpw1M7UbPIEaMVPL56GPT+5Igz/GTcpJBvSzhgnUlvG2WvWjnRoqgmPHXCQTs
            NyJsYnl0gpOrNZzcqCqJoyPN1FhWSsNpYgdxl9AsGIiDKE+NRscxChTnvycZHL7S
            XAF2FCM2pqr2WDZMpOIVMNZrynuqbm7Yev0f10wtPu9EeWbGOja2o940gzGTnpQn
            xKPY4LKtyIqA60ZYes7L1D0ICAnRlY4GAQnfvig5yzkY0SDFiBOCL31f1Tsn
            =y4+M
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2025-11-09T10:45:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/+IKZusOPQH/LYYEGDiWyV6WkgYVdDdbmGDwRkSN2VjhHH
            ieOanSYzK1EH8UrPYMv7n/2BjyX1FywA8v9zbflBJP8HgSrrAD3QHZ4sQIoZNRK6
            A+A51gP8M3BD6CZGMtZZZVAJiDyYU6yAvmausyHdYZxP78w3p/EBMqx9JmtG9N63
            Be+gXPqVjDKYRmWRKLizbesTI/Scat4PMw53qwKLYhBwjLullua8HPLhBFlZZx83
            VjV0c47/oNEb9ap040g8+s25vmO5oQYz49rxWoOzQKOAwT7IzunBo87jJyLj1tFc
            r58DHp//kHMWQFY4zZz753zlkg4jFkedvFBDDVAgsNyOVD0njmvCn3hwFzdmggZJ
            j/+RX9sQApoQW3n03GPRIp9JcLAF7YW/rFAi/nupGjW7wXlZ5i37S+m09NadA7sB
            MYjuJDbQYtj8o7qT+rB9YGzau3SVLN2NBu0tsp+mvairDztBRkIrUOANluOlE7pr
            Kv1xkZiTe2C2NSKmyM0g/VXmqhGa7ZzFBgA3fsv47x1T4KJ9FuCpmhvW/5yhBBsO
            RURy858mYrfGdgyr0VIHyzgaKzMrDgvKl1Yb9gwyIVazGwFahc+jFOv//ImcDade
            ZleaAZGqt73jDALCfHmFbk1S6t+gexKMI27whO38YZJu80fCHJpYW/si4dKajlTS
            XAFgtuZISGqsTA9xyGbaswMJhBfo+XxnJxliVMBVf36UfnGnZZmM7JAXBUXQFNPa
            c3tyxQA/74A0wxeVNS4g15JB/s1MXP0zRcuqvgrSQXAxmWazztT5BYbXBubg
            =9gzI
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.8.1
