apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openwebui
  namespace: b4mad-machdenstaat-oparl-lite-stage
spec:
  encryptedData:
    oauth-client-secret: AgBFELMrxS7iUBi9+nIBK49RQzrgIZ8Dqi/sx0fj13ZpNn36FLBdP+Rqw250hA550l7Y96ycQqyiIbbEg+v0xAgcdXPo0Te/VxS/wYI4f/g8wZHSnGjAXGJx/s/dfDCosKY0AvkidRwoQaq890L8aTW/WcywhEbQAVl/CNykbWQWxWb0I1VRq4usRL8PMhTaLDarE5vHRZZL4oUFVzn/4fgtBlumP+eaQwFTAcgmgAu+tJvGMjXhk2yXb8ZL5H5gN+cqDQCW6Br5RvjaL1PaTKlXhC6+g5zQn/ax/kn9YgxalTN9+pgkvM2sPmRYS1nINhgYbUKDvmTrl9rPDhY3PuBV9z2gznYVYPJ1JbCqsv0ejwr6vVI6ShyFFLRNvxu5o7xofS9crx47mlvaaJygnNjkuV2+/n+i5geZ+vdM8/JF38abhByFBiSSm9Us3/TMgRye2iKFnHAFy1smGbiu/r/qGe/csXpl7o5e5kzEnJUuN5qx+DK63tA6RdhDSgejKjgSsqaMnIdPnoNI8p+YjKwL2ps1azPmqUJYMcZ1r+bOD4Lzs8rEPHRAMv2i7oeHaIii4+fx7yZ5FzmrZLLc9L8jO0Emup3y4KgM0qpUXGDPacvfLHJLdUDEwAhEnIASXo0oNM7YvIylTdny4+xdTIl+H449uRR/2E9YZ1PW8evSm9KA7xjqlJ0/apHCvz2Xt2mFbi/YNfwp4QZZZmebBHenQdxb6tifshn0cfkBDZ3UeQ==
    webui-secret-key: AgAELVmw4b3j0nNbvyEgYuzHxs2U3Alih5zrIcZPkCUFY3gWiI2rTl7K9/xjsuikGjBfV9SRMJEWNqu0J9ACKUFv7SvtSPFthjPToYy2bTCEAQ6GIU/yESxNykCHoCgFZh1rh/hJm9A19t2rhrstE4TXQNsLgu8SjYjkXeIdyWnIJjksNdXAmuDQYTF6rr8tBkcOyFg666E5QRfFMPtjKf/XWfxSpX2Cn2SQfnE1bW6M2BBJ8KEFC1RTwrBfubBYZwlzDwa0zMvC7KaHdx2igIE8+RM4p8KAkyUT99NNGfNAhutF63BCGssPoeVOXQG+f+3ISVqpuBCKASj+jtOFOHrESrMrYBrfZKBoJ3Hf1kmSmCYxsadup/WmB2OsbBegzxZdFUjRWJvuZPYC8CPoQ9L6OF7hYlyylYEQUedvjvBlGSMNlNWzCF6Z07DklNOGM3nb21hBymwzHcLA7Ky5rjjMbEe4YtdJAyFAYkc3Zzdb9BGeYclF7kjqv9C3m3Vtoz3ZrEp/B7B7TtZJ1hMe4HB0HYGfrYbw+ltdcd1LHIT6xEkPqiON0I+BcIFr28Km9FkrIoUyrAjcZShOi8zh233ytiB9iJ2HvEDV1Rpg+ZpgIISwfbzVbEY6+bEifjAzFsuFbaHSpUk9lMQ5KOutqi9kztcgvf8w5I8F+BP0wWm1z+jAbw6qIeTD7vG3DOVeJzu3L5jlJ+G3FyItcL+csls9SA==
  template:
    metadata:
      creationTimestamp: null
      name: openwebui
      namespace: b4mad-machdenstaat-oparl-lite-stage
