apiVersion: v1
data:
    oauth-client-secret: ENC[AES256_GCM,data:jCARcXxBY+a4FTYA+nfTFw7YNrFuNA2zoZ4NQ1Iuhu0tT7Xf+ztxRDWG9Bo=,iv:i3NOXjSiKf9cZfmBvE2Z6G3JD2hNFWXzoyCq5rUgQ5c=,tag:luhrrtvYNRTXkfbNtdTpww==,type:str]
    webui-secret-key: ENC[AES256_GCM,data:QgJwkOn8iC5J2JNGdZrLz+wZjBBKTcC9,iv:arfK/i1KMwyqvaUX1vLPTO+3pzQVFxnyRAjn+JsQkBE=,tag:Uk3926056Z3SEtnxijzw6Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: openwebui
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-09T17:14:09Z"
    mac: ENC[AES256_GCM,data:U8xMvJre7r+Pvad7iwWZ2poZDqMb/SFE/bk3EA7eiD4LQZzr18xxLha0cXzUX2VkXvND+sKu+5+DYOiQnDPLkdGUERyEtpDqYx1G9VxgrnI0k8Akm1frgueBaoj95lCMoy5A2O/j5s0EPcdxjCOklxlofYKXKkIhLJqx5L9OWLI=,iv:vFArNA6gbpXN6yvViK560ghYycw8QnWDpwITXwljtw8=,tag:BUmYP4VMe+ceO1qtHSZIuA==,type:str]
    pgp:
        - created_at: "2025-11-09T17:14:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+XrDaMvM3KsARAAhRKLNlzlO9PVgTEhRJeMEG+NLh4ijnWBCsUKL5U9+aAJ
            5k8czL24i3QGMquGly3D+rBjXSj82c9TTmCZ12KVIwukMUQKIAcx+DawVfyzS6Ek
            iCC8q+WEmB8WZPEnUGpeIptMGbZPLK76IQFt2aIyfTF+kENjQYW2wJCH8Z06NmPP
            Kmvm5pr7WLWjcyYVsb90zE/Q7xcUj4/glSJNu8yXQmANAU/ITJLVK81mIEdnSGyD
            aCG/h7uf0deWsiV2tyXAwT1gGYxAVzfqwaE6CAgpWWRmEQF0PSJlk0Ci1t2gf//Z
            x3+/l6C7snScoGLyl54jpvSy0NmanZcMNfjLLsaTSnUAaxYHdNu1+UpTNVF1FkSH
            C/fu1drkMiOLjHN959qFw7NOdend4pMy1I21rUddTmIenM00Rr+aRbOUr3E4RyTQ
            m33KGcEGepi3kQFWgZikADjp/57wvUMP0Wn1bXeJB6wDK0IPQToW4FmbU0RLNqPF
            LJZ137QL1qs6m4KCUCIMWXm/ZZGsgSf/EBE7HLld5aQagsqY3DikM1XbrWHNBwn8
            7+EQH66kQtq5TxQBWEod+tIg5rC93pSsukZW2isChh777HUz8D6pCrUkXv4TZ1Lx
            AZ6tUBB+7UyzbLLVj4LwEVbYrbpA258nGupUCwzoVe2Z9w+7Obt9yqGCRhAJdHPS
            XgGnokBveFiEBMsqdq+g7baGyBXxR5UNW1TO5yge0xHpTyTuNq6K67u+GpZHFbpS
            6Vtqu7kJ6Mu2iWVA/QNSj7IEBI99Bm8QMHmeVGmLQ6LeFbQ0o+GD8U4VhNtHVLg=
            =pe5l
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2025-11-09T17:14:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAoI12ch+Le7NX/4cTQ6++0S/jZ5cbFJWD3KD1DmUg6Our
            Azsz4NXqWW1LRcjFtsOXoTd856lyIqaQCu4q3EaPYXbbeLhmYLGkdFe7syx7+nRz
            a5hHQy21+WmVZf7HDpkZ0zpn306forfr628y/pWyJSnKJ9aZS1vbUYk2ZDRxhF8/
            ++MY3EBjwe1qn2RefgX+f+e1m8+yZMxlvWL4AmZ6L43vKJowvXPJ43kSm/GIKMVJ
            43k9riO7oenACglS04o/67KF/G+3OQI+iOJsKxDmtG3d0LYSmFO9GvV2XqXJBQqp
            xQ6JRrrufaWHdfveKG6j+s4stivv+Kn5pazp/u1zdKBkIJy6wK5tNAydPtkNU9s4
            APr0/AIOEnMsTZ7y7cyzFBBGAN6FV7S6hEiDCRLHhXkWGCGCzlF6rH+WoLw30f8P
            OPiMqzF9vCD7XkJAvboWr7ex0Vkbjnw4BxEXsrDvaVUqtYbinanHDIOzGtUwEK0L
            9+tC2taXFcNicXymXkVlfEVkHIHet2gABtU2stNzrBYl6obqgOmFvPSeJXs2POmF
            UQ5RBl1zBRmApeZiKguqeJrAMEONnix1Nf0IBlkcE3JZAlPoKhxNP4wcC86Q48QA
            jPMKJhGoOk4el+LIvGNUY0h7BeaKjfgmpjkVF7y2P1lP50ilHrbOE0h0AvYbZh/S
            XgHtSALs1lMQRe3hE6gGuVn479+et4Xmuk4eMwD8mzW/WL3uCViBThfkR02Pp1ld
            hGvR5Nv3d/FruEPhW08m/TXNrROb+9hfJ5aThj7zxhHMnvCr1xkpi1dvnKM6X20=
            =BuE3
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.8.1
